Revert "xbps-src: relax check for writable hostdir."
This reverts commit 818d2d59cd4d0b832dd07698117e57f6d913e8df.

diff --git a/xbps-src b/xbps-src
--- a/xbps-src
+++ b/xbps-src
@@ -503,6 +503,9 @@ fi
 if [ -d "$XBPS_MASTERDIR" -a ! -w "$XBPS_MASTERDIR" ]; then
     echo "ERROR: can't write to masterdir $XBPS_MASTERDIR." 1>&2
     exit 1
+elif [ -d "$XBPS_HOSTDIR" -a ! -w "$XBPS_HOSTDIR" ]; then
+    echo "ERROR: can't write to hostdir: $XBPS_HOSTDIR."
+    exit 1
 fi
 
 # Try using chroot-git then git from the host system
